name: country_picker
description: A flutter package to select a country from a list of countries.

version: 1.0.5+13

homepage: https://github.com/Daniel-Ioannou
repository: https://github.com/Daniel-Ioannou/flutter_country_picker

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  universal_io: ^2.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter